### ISSUE TITLE
3.3.0 breaks TLS connection

### ISSUE THREAD

**Issue by kirrg001** [ibmdb/node-ibm_db#1009]
Hi there!

We have updated db2 from 3.2.5 to 3.3.0.

We are using IBM Cloud db2 instance.
> Version: Compatible with Db2, Version 11.5.0 or later

We are connecting from IBM Tekton CI/CD to the db2 instance.
The tests are running in a normal [Node.js docker container.](https://hub.docker.com/_/node)

We are suddenly getting on `ibmdb.open`:
```
[Error: [IBM][CLI Driver] SQL20576N  The command or operation failed because a TLS connection could not be established with reason "1" and additional information "169.50.5.10".  SQLSTATE=08001
@instana/collector: ] {
@instana/collector:   error: '[ibm_db] SQL_ERROR',
@instana/collector:   sqlcode: -20576,
@instana/collector:   state: '08001'
@instana/collector: }
```

Connection String did not change and looks like this:

> DATABASE=bludb;HOSTNAME=....databases.appdomain.cloud;UID=12345;PWD=12345;PORT=32354;PROTOCOL=TCPIP;SECURITY=SSL"

Thanks!

**Comment by bimalkjha** [comment]
@kirrg001 ibm_db@3.2.5 uses clidriver version 11.5.9 while ibm_db@3.3.0 uses clidriver version 12.1.0 by default which is latest release version of db2 client.
You can install ibm_db@3.3.0 with older clidriver using command: `npm install ibm_db -clidriver=v11.5.9`

To diagnose your TLS issue, we need db2traces. I would suggest to open file `.../ibm_db/installer/testODBCConnection.sh` in an editor and replace line 29 that have `db2cli validate` command with below command and run `testODBCConnection.sh` script:
```
db2cli validate -connString "DATABASE=bludb;HOSTNAME=....databases.appdomain.cloud;UID=12345;PWD=12345;PORT=32354;PROTOCOL=TCPIP;SECURITY=SSL" -connect
```
Capture the complete output of testODBCConnection.sh script in a file. zip this output file with all 1.* generated files and share here. Thanks.

**Comment by bimalkjha** [comment]
Note that in Db2 V12.1, by default SSLClientHostnameValidation is enabled: https://www.ibm.com/docs/en/db2/12.1?topic=transit-hostname-validation
i.e. if your SSL certificate do not have the hostname used in connection string, connection will fail. You can verify it by adding `SSLClientHostnameValidate=OFF;` in connection string. If certificate do not have hostname, using `SSLClientHostnameValidate=OFF;` in connection string should fix the issue. Thanks.

**Comment by kirrg001** [comment]
Hi!

> Version: Compatible with Db2, Version 11.5.0 or later

IBM Cloud supports 11.5.0 or **later**. I'd assume that clidriver v12 works as well.
I assume it means the IBM Cloud db2 instance only supports clidriver v11?

> SSLClientHostnameValidate=OFF

This suggestion is not working. Still the same error.

**Comment by kirrg001** [comment]
> npm install ibm_db -clidriver=v11.5.9

How to define that in our package.json?

**Comment by bimalkjha** [comment]
export npm_config_clidriver="v11.5.9"
OR,
npm config set clidriver v11.5.9
OR,
export IBM_DB_INSTALLER_URL=https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/v11.5.9/linuxx64_odbc_cli.tar.gz

**Comment by kirrg001** [comment]
I have added an `.npmrc` file. Works again.

.npmrc
> clidriver=v11.5.9

**Comment by kirrg001** [comment]
> @kirrg001 ibm_db@3.2.5 uses clidriver version 11.5.9 while ibm_db@3.3.0 uses clidriver version 12.1.0 by default which is latest release version of db2 client.

IMO this change should have been mentioned here:

https://github.com/ibmdb/node-ibm_db/blob/master/CHANGES.md#2024-12-01-version-330

And also: IMO this should have been shipped in a breaking change.

**Comment by lucaskuperman** [comment]
I was having the same issue. `SSLClientHostnameValidation=OFF` worked for me! Just make sure to type `SSLClientHostnameValidation` and not `SSLClientHostnameValidate`.
