### ISSUE TITLE
Stale connections in pool after database restart

### ISSUE THREAD

**Issue by jajuanMitchell** [ibmdb/node-ibm_db#569]
The following fix works in all cases except for when setting the isolation level on the connection from the pool.  
https://github.com/ibmdb/node-ibm_db/issues/327

The following code in the ibm_db does not have the check for error and to cleanup the pool like other calls . 

Database.prototype.setIsolationLevel = function(isolationLevel) 
{
  var self = this;
  return (self.conn.setIsolationLevel(isolationLevel));
};

It's missing : 

         if((initialErr && initialErr['message'] &&
              initialErr['message'].search("SQL30081N") != -1))
          {
            // Close all connections in availablePool as all are invalid now
            if (self.availablePool && self.availablePool.length) {
              for (var i=0, len = self.availablePool.length; i < len; i++) {
                self.availablePool[i].closeSync();
              }
            }
            self.closeSync();
          }

**Comment by jajuanMitchell** [comment]
Ok, after looking at the odbc.js code I see the problem.  The fix for stale connections that were added in https://github.com/ibmdb/node-ibm_db/issues/327 only fixes when there are queries ran directly from ibm_db.query  method.  Hence the fix is in Database.prototype.query method.

This does not fix the cases where the connection is stale and the query is execute from 
- odbc.ODBCStatement.prototype.executeNonQuery
- odbc.ODBCStatement.prototype.executeQuery

Also it does not handle stale connection for the following methods:
- conn.setIsolatonLevel
- conn.startTransaction
- conn.rollback
- conn.commit

**Comment by bimalkjha** [comment]
@jajuanMitchell We are looking into it. Your finding seems correct. I have added code to handle stale connections only for ibm_db.query method. Will add for others too. Give us some time.
Btw, if you can configure ACR using db2dsdriver.cfg file as commented [here](https://github.com/ibmdb/node-ibm_db/issues/270#issuecomment-311171336) and also mentioned in many other closed issues, stale connection problem will not occur for any API. Thanks.

**Comment by bimalkjha** [comment]
@jajuanMitchell Please install ibm_db@2.6.1 and verify the fix. This version has fix for this issue. Thanks.

**Comment by jajuanMitchell** [comment]
When I do a netstat I still see the connections not cleaned up.  Looks like the exception thrown from odbc.js line number 1413  does not invoke the pool cleanup method. 

ver] SQL30081N  A communication error has been detected. Communication protocol being used: \"TCP/IP\".  Communication API being used: \"SOCKETS\".  Location where the error was detected: \"::1\".  Communication function detecting the error: \"recv\".  Protocol specific error code(s): \"*\", \"*\", \"0\".  SQLSTATE=08001\n","stack":"Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: \"TCP/IP\".  Communication API being used: \"SOCKETS\".  Location where the error was detected:\"::1\".  Communication function detecting the error: \"recv\".  Protocol specific error code(s): \"*\", \"*\", \"0\".  SQLSTATE=08001\n","type":"Error","v":1}
{"level":50,"time":1567521565131,"pid":88149,"hostname":"Michaels-MBP.attlocal.net","file":"db2Connector","msg":"Cannot read property '0' of null","stack":"TypeError: Cannot read property '0' of null\n    at executeQuery (/Users/jajuan/git/solution-server/common/db2Connector.js:449:58)\n    at conn.close (/Users/jajuan/git/solution-server/common/db2Connector.js:268:6)\n    at Database.db.close (/Users/jajuan/git/solution-server/node_modules/ibm_db/lib/odbc.js:1989:18)\n    at cleanupAndInvokeCallBack (/Users/jajuan/git/solution-server/common/db2Connector.js:266:9)\n    at /Users/jajuan/git/solution-server/common/db2Connector.js:297:6\n    at /Users/jajuan/git/solution-server/node_modules/ibm_db/lib/odbc.js:1413:13","type":"Error","v":1}

**Comment by bimalkjha** [comment]
@jajuanMitchell stale connection will be cleaned after hitting first SQL30081N  by any connection method. Line 1413 is under statement.execute(). We can not have statement without getting the connection. If your application is keeping the statement open and after server restart calls execute(), then its something to be corrected in the application. Normally expectation is soon after getting statement, execute should be called on that statement. To get statement, we need to call a method on connection, in case of stale connection, that method will return SQL30081N  and clean the stale connections from pool. On receiving SQL30081N , application should get a fresh connection from pool and restart the operation. Hope, it clarifies. Thanks.

**Comment by jajuanMitchell** [comment]
@bimaljha thanks for the clarification.  We don't keep the statement open. We invoke execute and if it throws an exception we attempt to do cleanup by closing the statement and connection then doing a rollback.  Sounds like we need to check for SQL30081N and attempt to get another connection from the pool.  I can give that a try.

**Comment by jajuanMitchell** [comment]
@bimaljha still does not work.  After catching the exception and letting all all the db calls for that request fail then resubmitting the the request where it gets another connection from the pool you get 

CLI0600E Invalid connection handle or connection is closed. SQLSTATE=S1000","v":1} every time a connection from the pool is used.

**Comment by jajuanMitchell** [comment]
@bimalkjha I added break point in your Database.prototype.checkConnectionError code and it never gets called after line 1413 in the odbc.js returns SQL30081N hundreds of times

**Comment by bimalkjha** [comment]
@jajuanMitchell Please share a small test program to reproduce the problem, so that I can understand your application logic and investigate further. Thanks.

**Comment by bimalkjha** [comment]
Database.prototype.checkConnectionError will be called from any connection method only. Line 1413 is under statement method. So, any connection method called after 1413 should call Database.prototype.checkConnectionError. Thanks.

**Comment by jajuanMitchell** [comment]
@bimalkjha I see you have the fix in Database.prototype.prepare = function (sql, cb) method but how about odbc.ODBCStatement.prototype.prepare  which is what I'm calling ?

**Comment by jajuanMitchell** [comment]
Sorry, but we are using connection.prepare. I need to check that one

**Comment by jajuanMitchell** [comment]
@bimalkjha after more break points in odbc I see that the err object is always null in create statement and prepare statement so your fix is never invoked. However, when the code gets  to _execute it will have the SQL error "SQL30081N  A communication error has been detected. Communication protocol be .. "  

So in short, I don't think the statement methods invokes the database or the cli never returns an error for those calls but when you execute a query it does .

**Comment by sg-19** [comment]
@jajuanMitchell Did you get to a resolution? I am using 2.7.1 and still see the same problem you had faced. I don't think this stale connection problem is fixed yet.
